- index.html
In this commit, a boxed HTML page with CSS grid classes was added.
> Add index page

- css/grid.css
In this commit, the initial grid was added,.
> Add CSS grid

- css/main.css
In this commit, the box class was styled slightly to fit the page design.
> Add box styles

- index.html
In this commit, multiple changes were made to the HTML file to create a concise page structure.
> Update page structure

- css/grid.css
In this commit, styles were added inside media queries to create a responsive layout.
> Add responsive styles

- css/main.css
In this commit, several global styles were added to ensure a proper structure and multiple classes were added to facilitate future development.
> Add global styles

- css/grid.css
- css/main.css
In this commit, a positioning issue with the footer logo was solved.
> Fix footer logo styles

- index.html
In this commit, a few missing classes to the footer logo were added.
> Fix footer logo classes

- css/grid.css
- css/main.css
In this commit, the pallete for the webpage was added, as well as styles for the mobile and desktop menu.
> Add colors and menu styles

- js/main.js
In this commit, the mobile menu toggle was implemented and the menu can now reset when the window is resized.
> Add menu functionality

- css/grid.css
- css/main.css
In this commit, a small menu issue was corrected (lack of bold text on desktop version). Most footer styles were also added.
> Add footer styles and menu fixes

- index.html
In this commit, a few changes were made to help style the hero banner.
> Update hero banner

- css/grid.css
- css/main.css
In this commit, the hero banner was styled and the background image is now responsive. Additionally, the grid padding was changed.
> Add hero banner styles

- index.html
In this commit, classes were added to the event information container for future styling, and now certain words are uppercase.
> Update event information

- css/grid.css
- css/main.css
In this commit, the styles for the video and the event information container were added.
> Add video and event container styles

- index.html
In this commit, the slides, along with arrows and miniatures were added to the gallery container.
> Add gallery slider

- css/main.css
In this commit, all styles for the gallery container were added. Additionally, the slider was set up.
> Add gallery styles

- js/main.js
In this commit, the arrows and miniatures of the gallery container received functionality.
> Add slider functionality

- index.html
In this commit, the previous partners container was added with placeholder logos. The project container was also changed for further styling.
> Add partners container

- css/grid.css
- css/main.css
In this commit, both containers were styled for desktop and mobile screen sizes.
> Add partner container and project container styles

- index.html
In this commit, the menu, hero, video and event info containers were changed to create a clearer document.
> Fix containers #1

- index.html
In this commit, the partners, gallery and project info containers were improved.
> Fix containers #2

- css/grid.css
- css/main.css
In this commit, changes were made to the partner, gallery and project info containers to optimize styles.
> Fix container styles #2

- js/main.js
In this commit, the slider miniatures received proper functionality. Users are now able to change slides through them.
> Fix slider miniatures

- index.html
In this commit, the HTML file was linked to the plyr library.
> Link to plyr

- css/grid.css
- css/main.css
In this commit, the header styles were changed to accommodate a menu slide animation.
> Add header transitions

- js/main.js
In this commit, the menu slide transition was fixed and the spin transition was added.
> Fix transitions

- css/grid.css
- css/main.css
In this commit, horizontal scrolling was removed.
> Fix horizontal scroll

- README.md
In this commit, a small correction was added to the credits section
> Fix Readme #2

- index.html
In this commit, logo images and several image descriptions were added.
> Add logos and alt text

- css/grid.css
- css/main.css
In this commit, an issue with logos breaking the container was fixed. Logos now have fixed sizes.
> Fix logo sizes

- css/main.css
In this commit, text color was changed in certain containers.
> Fix invisible text

- css/grid.css
- css/main.css
In this commit grid.css and main.css was updated.
> grid.css and main.css

- css/main.css
In this commit, hover animations for various buttons were added to the page.
> Add hover animations

- index.html
In this commit, GreenSock was linked to the index page. Many static containers were removed and animated classes were added. Certain placeholder text was also changed.
> Prepare dynamic content and link to Green Sock

- css/grid.css
- css/main.css
In this commit, a few styles were changed as the showcase and finalist containers were merged.
> Fix showcase container

- css/main.css
In this commit, a simple opacity animation was added to the hero container.
> Add hero animation

- js/main.js
In this commit, arrays for the portfolio and testimonial contents were created, and added dynamically to the page.
> Add portfolio and testimonial content

- js/main.js
In this commit, scrollTrigger animations from the GreenSock library were added to make each container appear once its on viewport. Additionally, certain images will appear one by one.
> Add scrollTrigger animations

- css/main.css
In this commit, a fade animation for the gallery and a scale animation for the miniatures was added.
> Add gallery animations

- js/main.js
In this commit, the scale transition for miniatures when changed was added.
> Add miniature transition

- index.html
In this commit, many anchor tags received links, such as buttons that redirect the user and links for menu buttons.
> Add anchor tag links

- css/grid.css
- css/main.css
In this commit, smooth scrolling was added to the page and certain classes were changed due to buttons becoming anchor tags.
> Fix links and add smooth scrolling

- js/main.js
In this commit, a small bit of code was added to prevent the user from scrolling when the mobile menu is open.
> Prevent menu scrolling

- css/grid.css
- css/main.css
In this commit, the mobile header position was changed to sticky.
> Change fixed header

- index.html
In this commit, the new images were linked to the page and through the use of media queries, they will change according to screen size.
> Add responsive images

- css/grid.css
In this commit, along with a few adjustments to image sizing, responsive image classes were added to media queries.
> Add responsive image classes

- index.html
In this commit, certain classes were added and/or changed as they had repeated styles, and a fade animation for the hero and program info container was added.
> Add new classes and fade animation

- js/main.js
In this commit, a scroll triggered fade animation was created.
> Create fade animation

- index.html
In this commit, all remaining images were added.
> Add missing images

- images/x.svg
In this commit, a missing social media component was added.
> Add twitter icon

- css/grid.css
- css/main.css
In this commit, the program-info container's broken text was fixed, along with the text of student portfolios.
> Fix broken text and links

- js/main.js
In this commit, a small spelling mistake was corrected.
> Use correct grammar

- README.md
In this commit, the placeholder project description image was removed and the final file was added.
> Swap picture

- css/grid.css
In this commit, a small css error was corrected.
> Validate CSS

- .gitignore
In this commit, the assets folder was hid, along with its contents.
> Hide assets folder entirely
